### PR TITLE
Add DIS flow to classical approach

### PR DESCRIPTION
**Pull request by sagniknitr**
DIS flow is a very fast optical flow estimation algorithm. It is used in many SLAM implementations and smartphones because of its speed.

### CODE REVIEW

**Comment by sagniknitr** [comment]
@antran89 please review and merge!

**Review by antran89 — APPROVED** [review]
Thank you @sagniknitr for the contribution!

**Comment by antran89** [comment]
@sagniknitr sorry, i did not check github frequently :-). Hope you stay safe and well. Will check out your paper.

**Comment by sagniknitr** [comment]
Hi @antran89 ,  thanks for merging !!  Also thanks for starting and maintaining this repo. A little background, for one of my tasks related to video frame insertion I was searching for a fast and accurate enough solution and found DISFlow to be a very good candidate for a multi-core DSP processor.

**Pull request merged**
